"""확정된 영문 표기의 한국어 관용 읽기를 정의한다."""

from __future__ import annotations


CONVENTIONAL_READINGS = {
    "AIDS": "에이즈",
    "APEC": "에이펙",
    "ASCII": "아스키",
    "ASEAN": "아세안",
    "BIOS": "바이오스",
    "CCTV": "씨씨티비",
    "CESCO": "세스코",
    "COEX": "코엑스",
    "DGIST": "디지스트",
    "FEDEX": "페덱스",
    "FIFA": "피파",
    "FILA": "휠라",
    "GIST": "지스트",
    "IKEA": "이케아",
    "KAIST": "카이스트",
    "KATUSA": "카투사",
    "KIA": "기아",
    "KIST": "키스트",
    "KOSDAQ": "코스닥",
    "KOSPI": "코스피",
    "LAN": "랜",
    "LASEK": "라섹",
    "LASER": "레이저",
    "LASIK": "라식",
    "MERS": "메르스",
    "NASDAQ": "나스닥",
    "NASA": "나사",
    "NATO": "나토",
    "NIMBY": "님비",
    "OLED": "올레드",
    "PASS": "패스",
    "PAYCO": "페이코",
    "PIN": "핀",
    "POSTECH": "포스텍",
    "PUBG": "펍지",
    "RADAR": "레이더",
    "RAM": "램",
    "ROM": "롬",
    "SARS": "사스",
    "SCUBA": "스쿠버",
    "SSGPAY": "쓱페이",
    "TOEFL": "토플",
    "TOEIC": "토익",
    "TV": "티비",
    "TVN": "티비엔",
    "UNESCO": "유네스코",
    "UNICEF": "유니세프",
    "UNIST": "유니스트",
    "USIM": "유심",
}

INITIALISMS = frozenset(
    {
        "AI",
        "API",
        "AR",
        "ASR",
        "BBC",
        "BC",
        "CD",
        "CEO",
        "CIA",
        "CNN",
        "CTO",
        "CPU",
        "DNA",
        "FAQ",
        "GPU",
        "HTTP",
        "HTTPS",
        "ID",
        "IT",
        "KTX",
        "LLM",
        "LTE",
        "MRI",
        "NLP",
        "OCR",
        "PDF",
        "QA",
        "RAG",
        "RNA",
        "ROI",
        "SNS",
        "SQL",
        "SSD",
        "STT",
        "TTS",
        "UI",
        "URL",
        "USB",
        "UX",
        "VR",
    }
)
